In [9]:
#from transformers import BertForMaskedLM, BertTokenizer
#tokenizer = BertTokenizer.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')
#model = BertForMaskedLM.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')
#input_ids = tf.constant(tokenizer.encode()"Hello, my dog is cute"))[None, :]  # Batch size 1
#outputs = model(input_ids)
#last_hidden_states = outputs[0]

In [198]:
from transformers import BertForMaskedLM, BertTokenizer
tokenizer = BertTokenizer.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')
model = BertForMaskedLM.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')

dev_text = open('/home/sara/data_file_dev.text', "r")
dev_text = dev_text.readlines()

dev_text1 = []
for i in dev_text:
    dev_text1.append(i.replace('\n', ''))

#input_ids1 = []
#for i in dev_text1:
#    input_ids1.append(tokenizer(i, return_tensors="pt" ,add_special_tokens=True, truncation=True, max_length=512)["input_ids"])




In [146]:
#idp=tokenizer('This is a dog', return_tensors="pt" ,add_special_tokens=True, truncation=True, max_length=512) ["input_ids"]

#output = model(idp, labels=idp, output_hidden_states=True)
#loss, prediction_scores = output[:2]
#loss, prediction_scores

(tensor(6.2547, grad_fn=<NllLossBackward>),
 tensor([[[ -6.9620,  -6.9183,  -6.9974,  ...,  -0.5169,  -0.5316,  -0.4576],
          [ -5.9431,  -6.0246,  -5.8681,  ...,  -2.8440,  -3.4277,  -2.4338],
          [-14.4893, -14.7996, -13.9067,  ...,  -4.0919,  -6.3026,  -6.3577],
          [-12.1260, -12.1680, -11.7592,  ...,  -3.7836,  -5.7970,  -6.6233],
          [ -7.6951,  -7.7708,  -7.3414,  ...,  -2.5603,  -3.6216,  -3.7144],
          [-11.9993, -11.9228, -12.3006,  ...,  -2.9177,  -4.5408,  -3.7212]]],
        grad_fn=<AddBackward0>))

In [200]:
#dev data testing
#dev_data = open('/media/sara/Data1/data/data_file_dev.text', "r")
#dev_data1 = dev_data.readlines()
#dev_data1[0]

#idp1=tokenizer('<skip> in <skip> a [MASK] bilingual [MASK] manner <skip> ; <skip> she <skip> grew <skip> up <skip> <unk> <skip> ;', return_tensors="pt" ,add_special_tokens=True, truncation=True, max_length=512)["input_ids"]

#output1 = model(idp1, labels=idp1, output_hidden_states=True)
#loss, prediction_scores = output1[:2]
#loss, prediction_scores

#output1[-1]



(tensor([[[ 0.4363,  0.0812, -0.2647,  ...,  0.1679,  0.0949, -0.1662],
          [-0.8867, -0.3506, -1.2009,  ..., -0.6592, -0.4229,  0.4252],
          [-0.9950,  0.3549,  0.4712,  ..., -0.0035,  0.2137,  1.4897],
          ...,
          [ 0.3726,  0.6557, -0.3635,  ..., -0.5097,  1.1987,  0.9280],
          [-0.9275, -0.9602,  0.9621,  ..., -0.9020, -0.5340,  0.7442],
          [ 0.1445, -0.0523,  0.1561,  ...,  0.4010, -0.5532,  0.7137]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[[ 0.3024, -0.0114, -0.1102,  ...,  0.1267,  0.0044, -0.0890],
          [-1.1696,  0.1321, -1.3778,  ..., -0.8818, -0.3141,  0.2393],
          [-1.3820,  0.8519,  0.2753,  ..., -0.2223,  0.4391,  1.5038],
          ...,
          [ 0.3003,  0.7275, -0.7145,  ..., -0.8505,  0.8754,  1.4802],
          [-0.6544, -1.2697,  0.8514,  ..., -0.7269, -1.3505,  1.1388],
          [ 0.0832, -0.2768,  0.2476,  ...,  0.5885, -0.7519,  0.9834]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[[ 0.

In [190]:
#idp1=tokenizer('<skip> in <skip> a [MASK] bilingual [MASK] manner <skip> ; <skip> she <skip> grew <skip> up <skip> <unk> <skip> ;', return_tensors="pt" ,add_special_tokens=True, truncation=True, max_length=512)["input_ids"]

#output1 = model(idp1, labels=idp1, output_hidden_states=True)
#loss, prediction_scores = output1[:2]
#loss, prediction_scores

(tensor(2.4861, grad_fn=<NllLossBackward>),
 tensor([[[ -6.7320,  -6.6894,  -6.7908,  ...,  -0.5185,  -0.6558,  -0.5802],
          [ -8.6281,  -9.0553,  -8.6084,  ...,  -4.3362,  -6.7238,  -7.0533],
          [-14.9756, -14.8800, -14.7026,  ...,  -6.5278, -10.0090, -10.0526],
          ...,
          [-13.5688, -13.2074, -13.6273,  ...,  -6.0882,  -8.8954,  -7.2744],
          [-11.9454, -11.2604, -12.4151,  ...,  -4.9131,  -6.1512,  -7.3378],
          [-16.9721, -17.4291, -17.5651,  ...,  -6.1510, -11.6109, -10.2476]]],
        grad_fn=<AddBackward0>))

In [166]:
#output1[-1]

(tensor([[[ 0.4363,  0.0812, -0.2647,  ...,  0.1679,  0.0949, -0.1662],
          [-0.8867, -0.3506, -1.2009,  ..., -0.6592, -0.4229,  0.4252],
          [-0.9950,  0.3549,  0.4712,  ..., -0.0035,  0.2137,  1.4897],
          ...,
          [-0.5602,  0.4745,  0.5421,  ..., -0.1789,  0.3782,  1.9219],
          [ 0.0361,  0.6449, -0.2595,  ..., -0.4712,  1.2882,  0.8687],
          [-0.0122, -0.3497,  0.4039,  ...,  0.3345, -0.5762,  0.8033]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[[ 0.3003, -0.0144, -0.0802,  ...,  0.1209,  0.0209, -0.1190],
          [-1.1452,  0.0878, -1.1203,  ..., -0.8328, -0.4509,  0.1563],
          [-1.6059,  0.8189,  0.3099,  ..., -0.1426,  0.6523,  1.4276],
          ...,
          [-0.9239,  0.7867,  0.4670,  ..., -0.3214,  0.5979,  2.0904],
          [-0.0279,  0.5278, -0.4389,  ..., -0.7774,  0.9218,  1.2213],
          [-0.0688, -0.6462,  0.5994,  ...,  0.6509, -0.7973,  0.8518]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[[ 0.

In [168]:

from transformers import BertForMaskedLM, BertTokenizer
tokenizer = BertTokenizer.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')
model = BertForMaskedLM.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')

dev_text = open('/home/sara/data_file_dev.text', "r")
dev_text = dev_text.readlines()

dev_text1 = []
for i in dev_text:
    dev_text1.append(i.replace('\n', ''))



output_vocab = open('/media/sara/Data1/data/output_data/output_vocabulary0', "r")
output_vocab1 = output_vocab.readlines()
output_vocab2 = []
for i in output_vocab1:
    output_vocab2.append(i.replace('\n', ''))
output_vocab2

In [195]:
# a1546110 
# n3090856 
#print(tokenizer.encode('n1183166 n3090856 n5840431'))
#print(output_vocab1[136],output_vocab1[7],output_vocab1[121])

[101, 29132, 29003, 29117, 102]
n1183166
 n3090856
 n5840431



In [192]:
#input_vocab_dev = open('/media/sara/Data1/data/output_data/input_vocabulary0', "r")
#input_vocab_dev = input_vocab_semwng.readlines()


dev = open("/media/sara/Data1/data/output_data/dev", "r")
dev = dev.readlines()
#lists of indices of sentences, senses and multiple senses
sentence_dev_indices = dev[0::3]
sense_dev_indices = dev[1::3]
multiple_sense_dev_indices = dev[2::3]

In [193]:
multiple_sense_dev_indices[0]

'0 0 3376 136;7;121 0 0 0 0 0 0 \n'

In [196]:
#prediction_scores[0, 11, [29132, 29003, 29117]]

tensor([ 5.5210, 14.5079,  5.9282], grad_fn=<IndexBackward>)

In [189]:
#output_vocab1[7]

'n3090856\n'

In [ ]:
#[tokenizer.ids_to_tokens[idx] for idx in tokenizer.encode(text)]

In [113]:
#output[-1][0][0,1,:]

tensor([-1.6873e+00, -1.1970e-01,  8.0339e-01,  7.4460e-01, -1.1575e+00,
         6.1963e-01, -2.2811e-01,  4.5309e-01,  3.3346e-01, -7.4832e-01,
         7.2152e-01, -5.8919e-01, -5.6245e-01,  9.2249e-01, -9.4111e-01,
        -1.3531e+00, -7.2941e-02,  1.3090e+00,  5.2788e-01, -1.3521e+00,
         4.7216e-01, -1.2822e+00,  8.1828e-01,  1.9771e-01,  1.4247e-01,
         8.0768e-01, -8.1271e-01,  3.6184e-01,  6.7449e-01, -1.4624e-03,
        -1.0910e+00, -1.9433e+00, -1.5685e-01,  6.0458e-01, -1.7944e-01,
         1.6760e-01, -1.8870e-01,  5.9226e-01, -5.0297e-01, -2.1214e-01,
         9.1401e-01, -6.3440e-01, -4.6790e-02,  1.1660e-01, -1.0316e+00,
        -4.8881e-01, -2.0424e-01,  6.0588e-01,  7.4007e-01, -1.3802e-01,
        -1.4054e+00, -3.3620e-01, -9.0837e-01,  1.6171e-01, -7.0828e-01,
        -1.0462e+00,  5.5187e-01,  1.1496e+00,  6.8534e-01, -6.9943e-01,
         4.2949e-01,  4.7305e-01,  5.6668e-01,  2.5313e-01,  5.7165e-01,
         4.5298e-01,  7.8856e-01, -4.5261e-01,  3.4

In [191]:
#text = '<skip> in <skip> a [MASK] bilingual [MASK] manner <skip> ; <skip> she <skip> grew <skip> up <skip> <unk> <skip> ;'
#[tokenizer.ids_to_tokens[idx] for idx in tokenizer.encode(text)]

['[CLS]',
 '<',
 'skip',
 '>',
 'in',
 '<',
 'skip',
 '>',
 'a',
 '[MASK]',
 'bilingual',
 '[MASK]',
 'manner',
 '<',
 'skip',
 '>',
 ';',
 '<',
 'skip',
 '>',
 'she',
 '<',
 'skip',
 '>',
 'grew',
 '<',
 'skip',
 '>',
 'up',
 '<',
 'skip',
 '>',
 '<',
 'un',
 '##k',
 '>',
 '<',
 'skip',
 '>',
 ';',
 '[SEP]']

In [81]:
#output = model(idp, labels=idp, output_hidden_states=True)
#loss, prediction_scores = output[:2]
#loss, prediction_scores

(tensor(6.2547, grad_fn=<NllLossBackward>),
 tensor([[[ -6.9620,  -6.9183,  -6.9974,  ...,  -0.5169,  -0.5316,  -0.4576],
          [ -5.9431,  -6.0246,  -5.8681,  ...,  -2.8440,  -3.4277,  -2.4338],
          [-14.4893, -14.7996, -13.9067,  ...,  -4.0919,  -6.3026,  -6.3577],
          [-12.1260, -12.1680, -11.7592,  ...,  -3.7836,  -5.7970,  -6.6233],
          [ -7.6951,  -7.7708,  -7.3414,  ...,  -2.5603,  -3.6216,  -3.7144],
          [-11.9993, -11.9228, -12.3006,  ...,  -2.9177,  -4.5408,  -3.7212]]],
        grad_fn=<AddBackward0>))

In [122]:
#prediction_scores.shape

torch.Size([1, 6, 38651])

In [101]:
#idp=tokenizer('This is a dog', return_tensors="pt" ,add_special_tokens=True, truncation=True, max_length=512) ["input_ids"]
#examples = idp["input_id"]
#output = model(idp, labels=idp, output_hidden_states=True)
#loss, prediction_scores = output[:2]
#loss, prediction_scores
#output[-1]

(tensor([[[ 4.3626e-01,  8.1177e-02, -2.6468e-01,  ...,  1.6788e-01,
            9.4910e-02, -1.6615e-01],
          [-1.6873e+00, -1.1970e-01,  8.0339e-01,  ...,  5.5771e-01,
            3.9032e-01,  3.1871e-01],
          [-1.2756e+00,  1.3298e-01,  6.3674e-01,  ...,  4.9545e-01,
            1.0655e+00,  6.9002e-01],
          [-6.9046e-01,  6.6751e-01, -4.3690e-01,  ..., -8.9179e-04,
            8.7874e-01,  3.3938e-01],
          [-8.5217e-02, -1.4988e+00, -1.2086e-02,  ..., -3.6683e-01,
           -1.1169e+00, -1.4308e+00],
          [-3.7903e-01,  3.0682e-01,  4.1093e-02,  ...,  7.3253e-01,
           -7.7188e-01, -8.3639e-02]]], grad_fn=<NativeLayerNormBackward>),
 tensor([[[ 0.3252, -0.1067, -0.0770,  ...,  0.1100,  0.0909, -0.1185],
          [-1.7292, -0.2550,  0.8500,  ...,  0.9083,  0.0997,  0.1904],
          [-1.1614,  0.0236,  0.4180,  ...,  0.6537,  0.6537,  0.7476],
          [-0.9002,  0.2695, -0.3768,  ...,  0.2363,  0.5075,  0.4436],
          [ 0.4908, -1.7389,  0.

In [214]:
#s = dev_data1[0]
#d = s.split()
#d

['<skip>',
 'in',
 '<skip>',
 'a',
 'a1546110',
 'bilingual',
 'n3090856',
 'manner',
 '<skip>',
 ';',
 '<skip>',
 'she',
 '<skip>',
 'grew',
 '<skip>',
 'up',
 '<skip>',
 '<unk>',
 '<skip>',
 ';']

In [218]:
#d[0::2]

['<skip>',
 '<skip>',
 'a1546110',
 'n3090856',
 '<skip>',
 '<skip>',
 '<skip>',
 '<skip>',
 '<skip>',
 '<skip>']

In [281]:
#multiple_sense_dev_indices 
#multiple_sense_dev_indices1 = [i.replace('\n', '') for i in multiple_sense_dev_indices] # removing \n
    
#multiple_sense_dev_indices2= [x.split(' ')for x in multiple_sense_dev_indices1] 

#multiple_sense_dev_indices3 = []
#for x in multiple_sense_dev_indices2:
#    indice = x.split(';')
#    for o in indice:
        

In [ ]:
from transformers import BertForMaskedLM, BertTokenizer
tokenizer = BertTokenizer.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')
model = BertForMaskedLM.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')

dev_text = open('/home/sara/data_file_dev.text', "r")
dev_text = dev_text.readlines()

dev_text1 = []
for i in dev_text:
    dev_text1.append(i.replace('\n', ''))

output_vocab = open('/media/sara/Data1/data/output_data/output_vocabulary0', "r")
output_vocab1 = output_vocab.readlines()
output_vocab2 = []
for i in output_vocab1:
    output_vocab2.append(i.replace('\n', ''))
output_vocab2

In [ ]:

#input_vocab_dev = open('/media/sara/Data1/data/output_data/input_vocabulary0', "r")
#input_vocab_dev = input_vocab_semwng.readlines()


dev = open("/media/sara/Data1/data/output_data/dev", "r")
dev = dev.readlines()

#lists of indices of sentences, senses and multiple senses
sentence_dev_indices = dev[0::3]
sense_dev_indices = dev[1::3]
multiple_sense_dev_indices = dev[2::3]

In [757]:
a

[10, 2, 3, 4, 5, 10, 2, 3, 4, 5, 10]

In [330]:

multiple_sense_dev_indices 
multiple_sense_dev_indices1 = [i.replace('\n', '') for i in multiple_sense_dev_indices] # removing \n
    
multiple_sense_dev_indices2= [x.split(' ')for x in multiple_sense_dev_indices1] 


a = []
for sentence in multiple_sense_dev_indices2:
    sense_position_new = []
    for sense_position in sentence:
        if sense_position == '':
            continue
        sense_position_new.append(sense_position.split(';'))
    a.append(sense_position_new)
a

[[['0'],
  ['0'],
  ['3376'],
  ['136', '7', '121'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0']],
 [['0'],
  ['0'],
  ['0'],
  ['0'],
  ['369', '2', '898', '1697'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['68',
   '1596',
   '1320',
   '438',
   '1208',
   '186',
   '57',
   '142',
   '231',
   '129',
   '117',
   '253',
   '1194',
   '407',
   '20',
   '63',
   '17',
   '139',
   '1497'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['284', '203', '228', '287', '333'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['37',
   '105',
   '436',
   '3302',
   '279',
   '1452',
   '5027',
   '2672',
   '527',
   '5969',
   '4084'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0'],
  ['0']],
 [['0'],
  ['67', '6', '31',

In [ ]:
from transformers import BertForMaskedLM, BertTokenizer
tokenizer = BertTokenizer.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')
model = BertForMaskedLM.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')

dev_text = open('/home/sara/data_file_dev.text', "r")
dev_text = dev_text.readlines()

dev_text1 = []
for i in dev_text:
    dev_text1.append(i.replace('\n', ''))


output_vocab = open('/media/sara/Data1/data/output_data/output_vocabulary0', "r")
output_vocab1 = output_vocab.readlines()
output_vocab2 = []
for i in output_vocab1:
    output_vocab2.append(i.replace('\n', ''))
output_vocab2

In [7]:
# getting list of all prepared sentences
def get_dev_text():
    dev_text = open('/home/sara/data_file_dev.text', "r")
    dev_text = dev_text.readlines()

    dev_text1 = []
    for i in dev_text:
        dev_text1.append(i.replace('\n', ''))
    return dev_text1


#getting list of all possible senses of sense word sentences
def get_senses():
    output_vocab = open('/media/sara/Data1/data/output_data/output_vocabulary0', "r")
    output_vocab1 = output_vocab.readlines()
    output_vocab2 = []
    for i in output_vocab1:
        output_vocab2.append(i.replace('\n', ''))
    
    dev = open("/media/sara/Data1/data/output_data/dev", "r")
    dev = dev.readlines()
    
    #lists of indices of sentences, senses and multiple senses
    sentence_dev_indices = dev[0::3]
    sense_dev_indices = dev[1::3]
    multiple_sense_dev_indices = dev[2::3]

    multiple_sense_dev_indices 
    multiple_sense_dev_indices1 = [i.replace('\n', '') for i in multiple_sense_dev_indices] # removing \n

    multiple_sense_dev_indices2= [x.split(' ')for x in multiple_sense_dev_indices1] 


    a = []
    for sentence in multiple_sense_dev_indices2:
        sense_position_new = []
        for sense_position in sentence:
            if sense_position == '':
                continue
            sense_position_new.append(sense_position.split(';'))
        a.append(sense_position_new)

    senses = []
    for sentence in a:
        senses1 = []
        for sense_position in sentence:
            senses2 = []
            for sense_index in sense_position:
                try:
                    sense_index_int = int(sense_index)
                    sense = output_vocab2[sense_index_int]
                    senses2.append(sense)
                except Exception:
                    print(f'sense_index: {sense_index}')
                    print(f'sense_position: {sense_position}')
                    print(f'sentence: {sentence}')
                    raise Exception
            senses1.append(senses2)
        senses.append(senses1)
    return senses


In [2]:
#Masking senses having multiple senses in sentence

def convert_list_to_string(org_list, seperator=' '):
    """ Convert list to string, by joining all item in list with given separator.
        Returns the concatenated string """
    return seperator.join(org_list)

def data_preparation(sentence, sentence_senses):
    
    sentence_splitted = sentence.split(' ')

    multisense_sentence = []   #multisense senses of the sentence
    multi_sense_index = []  # index of sense (having multiple senses) in senses
    for index, element in enumerate(sentence_senses):
        if len(element) > 1:
            multi_sense_index.append(index)
            multisense_sentence.append(element)
    #to get correct sense
    index_sent = [] #index of multisenses senses in sentence
    for i in multi_sense_index:
        ind_sent  = i*2
        index_sent.append(ind_sent)
    correct_sense = []
    for index, element in enumerate(sentence_splitted):
        for ind in index_sent:

            if index == ind:
                correct_sense.append(element)

    sentence_list = sentence.split(' ') #converting sentence string into list of strings of indivudual words
    #masking multisenses sense            
    sentence_list = sentence.split(' ')
    for ind in index_sent:
        sentence_list[ind] = '[MASK]'
    final_sentence = convert_list_to_string(sentence_list)
    return final_sentence, multisense_sentence, correct_sense

In [711]:
final_sent, multisense_sentence, correct_sense = data_preparation(dev_text1[0], senses[0])

In [704]:
print(multisense_sentence) 
print(correct_sense)
print(final_sentence)

[['n1183166', 'n3090856', 'n5840431']]
['n3090856']
<skip> in <skip> a a1546110 bilingual [MASK] manner <skip> ; <skip> she <skip> grew <skip> up <skip> <unk> <skip> ;


In [3]:
def model_prediction(final_sentence, tokenizer, model):
    idp=tokenizer(final_sentence, return_tensors="pt" ,add_special_tokens=True, truncation=True, max_length=512) ["input_ids"]
    output = model(idp, labels=idp, output_hidden_states=True)
    loss, prediction_scores = output[:2]
    output_hidden_states = output[-1]
    #print(loss, prediction_scores)
    return prediction_scores, loss, output_hidden_states

In [721]:
prediction_scores, loss, output_hidden_states= model_prediction(final_sent, tokenizer, model)

In [4]:
import numpy as np

def result_comparison(final_sent, correct_sense, prediction_scores, multisense_sentence, tokenizer):

    tokenized_final_sentence = np.array([tokenizer.ids_to_tokens[idx] for idx in tokenizer.encode(final_sent)])
    mask_indices = np.where(tokenized_final_sentence == '[MASK]')[0] 
    
    correct = 0
    incorrect = 0
    for j in range(len(correct_sense)):
        tokenizer_id = []
        for i in multisense_sentence[j]:
            tokenizer_id.append(tokenizer.vocab[i])


        pred_scor = prediction_scores[0,mask_indices[j], tokenizer_id]
        sense_masked1  = multisense_sentence[j] # list of multiple senses of first masked sense in the sentence


        eval1 = sense_masked1 [pred_scor.argmax()] #maximum prediction score among senses
        if eval1 == correct_sense[j]:
            correct += 1
        else:
            incorrect += 1
    return correct, incorrect

In [726]:
result_comparison(mask_indices, correct_sense, prediction_scores, multisense_sentence)

(1, 0)

In [27]:
from transformers import BertForMaskedLM, BertTokenizer
def prelimanaries():
    dev_text1 = get_dev_text()
    senses = get_senses()
    tokenizer = BertTokenizer.from_pretrained('/media/sara/Data1/data/bert_training_l2l_256block/')
    model = BertForMaskedLM.from_pretrained('/media/sara/Data1/data/bert_training_l2l_256block/checkpoint-2500/')
    total_correct  = 0
    total_incorrect = 0
    for l in range(len(dev_text1)):
        sentence = dev_text1[l]
        sentence_senses = senses[l]
        final_sent, multisense_sentence, correct_sense = data_preparation(sentence, sentence_senses)
        prediction_scores, loss, output_hidden_states= model_prediction(final_sent, tokenizer, model)
        correct, incorrect = result_comparison(final_sent, correct_sense, prediction_scores, multisense_sentence, tokenizer)
        total_correct += correct
        total_incorrect += incorrect
    return total_correct, total_incorrect, total_correct/(total_correct+total_incorrect)

In [28]:
prelimanaries()

(5823, 4287, 0.5759643916913947)

In [735]:
tokenizer = BertTokenizer.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')
model = BertForMaskedLM.from_pretrained('/media/sara/Data1/data/bert_training_semwng_fulltext/')
total_correct  = 0
total_incorrect = 0
for l in range(len(dev_text1)):
    sentence  = dev_text1[l]
    sentence_senses = senses[l]
    final_sent, multisense_sentence, correct_sense = data_preparation(sentence, sentence_senses)
    prediction_scores, loss, output_hidden_states, mask_indices= model_prediction(final_sent, tokenizer, model)
    correct, incorrect = result_comparison(mask_indices, correct_sense, prediction_scores, multisense_sentence)
    total_correct += correct
    total_incorrect += incorrect

In [748]:
del output_hidden_states, multisense_sentence, prediction_scores

In [22]:
5652/(5652+4458)

0.5590504451038576